from pytrader.config import USER_LONG_TERM_TRADE_RATIO, USER_SHORT_TERM_TRADE_RATIO, USER_RISK_PARITY_RATIO


def test_trade_ratios():
    assert (USER_RISK_PARITY_RATIO + USER_SHORT_TERM_TRADE_RATIO + USER_LONG_TERM_TRADE_RATIO) == 1
