# This workflow will install Python dependencies, run tests and lint with a single version of Python.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Test
on:
  push:
    branches: [ main ]

jobs:
  build:
    environment:
      name: .env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
         ALPACA_PAPER_KEY: ${{ secrets.ALPACA_PAPER_KEY }}
         ALPACA_PAPER_SECRET: ${{ secrets.ALPACA_PAPER_SECRET }}
         ALPACA_PAPER_ADDRESS: ${{secrets.ALPACA_PAPER_ADDRESS}}
         ALPACA_PAPER_ACCOUNT_NUMBER: ${{ secrets.ALPACA_PAPER_ACCOUNT_NUMBER }}
         ALPACA_PAPER_WEBSOCKET: ${{secrets.ALPACA_PAPER_WEBSOCKET}}
         SQL_SERVER_HOST: ${{ secrets.SQL_SERVER_HOST }}
         SQL_SERVER_DATABASE: ${{ secrets.SQL_SERVER_DATABASE }}
         SQL_SERVER_USER: ${{ secrets.SQL_SERVER_USER }}
         SQL_SERVER_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
         SQL_SERVER_TRADES_TABLE: ${{ secrets.SQL_SERVER_TRADES_TABLE }}
         SQL_SERVER_TRADES_TABLE_COLUMN_NAME: ${{ secrets.SQL_SERVER_TRADES_TABLE_COLUMN_NAME }}
         SQL_SERVER_TRADES_TABLE_COLUMN_ORDER_TYPE: ${{ secrets.SQL_SERVER_TRADES_TABLE_COLUMN_ORDER_TYPE }}
         SQL_SERVER_TRADES_TABLE_COLUMN_QUANTITY: ${{ secrets.SQL_SERVER_TRADES_TABLE_COLUMN_QUANTITY }}
         SQL_SERVER_TRADES_TABLE_COLUMN_ORDER_ID: ${{ secrets.SQL_SERVER_TRADES_TABLE_COLUMN_ORDER_ID }}
         SQL_SERVER_TRADES_TABLE_COLUMN_TIMESTAMP: ${{ secrets.SQL_SERVER_TRADES_TABLE_COLUMN_TIMESTAMP }}
         SQL_SERVER_TRADES_TABLE_COLUMN_ASSET_TYPE: ${{ secrets.SQL_SERVER_TRADES_TABLE_COLUMN_ASSET_TYPE }}
         SQL_SERVER_OPEN_TRADES_TABLE: ${{ secrets.SQL_SERVER_OPEN_TRADES_TABLE }}
         SQL_SERVER_OPEN_TRADES_COLUMN_NAME: ${{ secrets.SQL_SERVER_OPEN_TRADES_COLUMN_NAME }}
         SQL_SERVER_OPEN_TRADES_COLUMN_ASSET_TYPE: ${{ secrets.SQL_SERVER_OPEN_TRADES_COLUMN_ASSET_TYPE }}
         SQL_SERVER_OPEN_TRADES_COLUMN_ORDER_TYPE: ${{ secrets.SQL_SERVER_OPEN_TRADES_COLUMN_ORDER_TYPE }}
         SQL_SERVER_OPEN_TRADES_COLUMN_TRADE_INTENT: ${{ secrets.SQL_SERVER_OPEN_TRADES_COLUMN_TRADE_INTENT }}
         SQL_SERVER_OPEN_TRADES_COLUMN_QUANTITY: ${{ secrets.SQL_SERVER_OPEN_TRADES_COLUMN_QUANTITY }}
         SQL_SERVER_OPEN_TRADES_COLUMN_ORDER_ID: ${{ secrets.SQL_SERVER_OPEN_TRADES_COLUMN_ORDER_ID }}
         SQL_SERVER_OPEN_TRADES_COLUMN_LAST_UPDATED: ${{ secrets.SQL_SERVER_OPEN_TRADES_COLUMN_LAST_UPDATED }}
         SQL_SERVER_BUY_SELL_THRESHOLDS_TABLE: ${{ secrets.SQL_SERVER_BUY_SELL_THRESHOLDS_TABLE }}
         SQL_SERVER_BUY_SELL_THRESHOLDS_COLUMN_NAME: ${{ secrets.SQL_SERVER_BUY_SELL_THRESHOLDS_COLUMN_NAME }}
         SQL_SERVER_BUY_SELL_THRESHOLDS_COLUMN_BUY: ${{ secrets.SQL_SERVER_BUY_SELL_THRESHOLDS_COLUMN_BUY }}
         SQL_SERVER_BUY_SELL_THRESHOLDS_COLUMN_SELL: ${{ secrets.SQL_SERVER_BUY_SELL_THRESHOLDS_COLUMN_SELL }}
         SQL_SERVER_BUY_SELL_THRESHOLDS_COLUMN_LAST_UPDATED: ${{ secrets.SQL_SERVER_BUY_SELL_THRESHOLDS_COLUMN_LAST_UPDATED }}
         SQL_SERVER_WINDOWS_TABLE: ${{ secrets.SQL_SERVER_WINDOWS_TABLE }}
         SQL_SERVER_WINDOWS_COLUMN_NAME: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_NAME }}
         SQL_SERVER_WINDOWS_COLUMN_SMA_SHORT_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_SMA_SHORT_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_SMA_LONG_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_SMA_LONG_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_SMA_LONG_HOLD: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_SMA_LONG_HOLD }}
         SQL_SERVER_WINDOWS_COLUMN_EMA_SHORT_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_EMA_SHORT_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_EMA_LONG_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_EMA_LONG_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_EMA_LONG_HOLD: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_EMA_LONG_HOLD }}
         SQL_SERVER_WINDOWS_COLUMN_MACD_FAST_SHORT_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_MACD_FAST_SHORT_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_MACD_SLOW_SHORT_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_MACD_SLOW_SHORT_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_MACD_SIG_SHORT_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_MACD_SIG_SHORT_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_MACD_FAST_LONG_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_MACD_FAST_LONG_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_MACD_SLOW_LONG_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_MACD_SLOW_LONG_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_MACD_SIG_LONG_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_MACD_SIG_LONG_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_MACD_FAST_LONG_HOLD: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_MACD_FAST_LONG_HOLD }}
         SQL_SERVER_WINDOWS_COLUMN_MACD_SLOW_LONG_HOLD: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_MACD_SLOW_LONG_HOLD }}
         SQL_SERVER_WINDOWS_COLUMN_MACD_SIG_LONG_HOLD: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_MACD_SIG_LONG_HOLD }}
         SQL_SERVER_WINDOWS_COLUMN_RSI_SHORT_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_RSI_SHORT_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_RSI_LONG_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_RSI_LONG_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_RSI_LONG_HOLD: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_RSI_LONG_HOLD }}
         SQL_SERVER_WINDOWS_COLUMN_VOL_SHORT_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_VOL_SHORT_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_VOL_LONG_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_VOL_LONG_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_VOL_LONG_HOLD: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_VOL_LONG_HOLD }}
         SQL_SERVER_WINDOWS_COLUMN_BOLB_SHORT_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_BOLB_SHORT_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_BOLB_LONG_TRADE: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_BOLB_LONG_TRADE }}
         SQL_SERVER_WINDOWS_COLUMN_BOLB_LONG_HOLD: ${{ secrets.SQL_SERVER_WINDOWS_COLUMN_BOLB_LONG_HOLD }}
         AWS_IAM_USERNAME: ${{ secrets.AWS_IAM_USERNAME }}
         AWS_IAM_PASSWORD: ${{ secrets.AWS_IAM_PASSWORD }}
         AWS_IAM_KEY: ${{ secrets.AWS_IAM_KEY }}
         AWS_IAM_SECRET: ${{ secrets.AWS_IAM_SECRET }}
         AWS_REGION: $ {{ secrets.AWS_REGION }}
         AWS_IAM_CONSOLE_LOGIN_LINK: ${{ secrets.AWS_IAM_CONSOLE_LOGIN_LINK }}
         AWS_MODEL_BUCKET_NAME: ${{ secrets.AWS_MODEL_BUCKET_NAME }}

      run: |
        pytest