import enum


class Signal(enum.Enum):
    TRADE_MANAGER = "TRADE_MANAGER"
    RISK_PARITY_MANAGER = "RISK_PARITY_MANAGER"
    EXCHANGE_MANAGER = "EXCHANGE_MANAGER"


class Sender(enum.Enum):
    TRADE_MANAGER = "TRADE_MANAGER"
    RISK_PARITY_MANAGER = "RISK_PARITY_MANAGER"
    EXCHANGE_MANAGER = "EXCHANGE_MANAGER"

